In [16]:
import pandas as pd
p="/Users/tanay/Desktop/Multi-Agent Financial Copilot/data/compliance_benchmark.csv"
df=pd.read_csv(p)
df

,question,ground_truth,context
0,According to the 1999 working paper authored b...,"The title of the working paper is ""The Politic...",G66G111G108G116G111G110G44G32 G80G46G44G32 G97...
1,How do the costs of fire sales of assets in ma...,The costs of fire sales of assets in market eq...,G114G101G100G117G99G101G100G32 G105G110G118G10...
2,Under the capital requirements suggested under...,"Under the Basel III capital requirements, cons...",G84G104G101G32 G110G101G119G32 G99G97G112G105G...
3,"Under table-7.2.12, how does the projected imp...","When RWAs are unchanged, a one-percentage poin...",G65G32G111G110G101G45G112G101G114G99G101G110G1...
4,What table identifier and subject heading are ...,"Table 6.5, titled 'Indicative Benchmarks for L...",G84G65G66G76G69G32G45G32G54G46G53 G73G110G100G...
5,Under what specific regulatory provision of Re...,Apple Inc. omitted the instruments pursuant to...,* Indicates management contract or compensator...
6,If a wire transfer's ordering financial instit...,It qualifies as a cross-border wire transfer. ...,- e. Cross-border wire transfer: Cross-border ...
7,Based on the provided financial statement data...,'Inventories' reported a positive adjustment o...,"| Net income | Net income | Net income | 112,0..."
8,How is Systemic Risk described in relation to ...,Systemic Risk refers to the risk faced by the ...,G50G55G46 G84G104G101G114G101G32G105G115G32 G1...
9,Which regulatory circular containing the code ...,The circular containing '12.05.001' issued in ...,| 123. | UBD.BPD.CO./NSB1/11/12.03.000/ 2009-1...
10,For Senior Management (such as Whole Time Dire...,The entity can satisfy the requirement by decl...,| Entity Level | Board Resolution @@ | Exempte...
11,Based on the regulatory filing excerpt for App...,Apple Inc.'s state of incorporation is Califor...,| | | |\n|----|----|----|\n| | | |\n\ng66145g6...
12,"In 2025, how did the portion of the Company's ...","In 2025, indirect distribution channels accoun...",Markets and Distribution\n\nThe Company's cust...
13,Under the section labeled 'G83G99G101G110G97G1...,The three values reported for 'G50G48G49G54' u...,| G50G48G49G54 | G50G44G56G53G44G55G53G53G46G5...
14,Under the model assumptions where the cost of ...,Short-term debt is defined as having a maturit...,G73G102G32G116G104G101G32G99G111G115G116G32G11...
15,"Based on the author's calculations table, what...",When RWAs is at its lowest recorded level of 7...,| G40 G114 G69 G116 G32G45 G114 G76G105G97G98 ...
16,Comparing the two cited papers co-authored by ...,"""The Economics of Bank Regulation"" was publish...",G66G104G97G116G116G97G99G104G97G114G121G97G44G...
17,"Based on Apple Inc.'s 2025 Form 10-K, how did ...","Fiscal year 2023 spanned 53 weeks, whereas fis...","Fourth Quarter 2025:\n\n• iPhone 17, iPhone Ai..."
18,What is the working paper number and publicati...,"The publication is Working Paper 14631, publis...",G84G97G121G108G111G114G44G32 G74G111G104G110G4...
19,What initial step is outlined to capture the e...,The initial step is analyzing the basic concep...,G73G110G32G111G114G100G101G114G32G116G111G32G9...

In [17]:
d=pd.read_csv("data/final_evaluation_report.csv")

In [18]:
d

,user_input,retrieved_contexts,response,reference,faithfulness,answer_correctness,context_precision,context_recall,num_contexts,is_safe,is_compliant,web_search_used,loop_count
0,According to the 1999 working paper authored b...,['| [Item 8.](#i719388195b384d85a4e238ad88eba9...,The provided sources do not contain informatio...,"The title of the working paper is ""The Politic...",1.000000,0.201607,0.000000,0.0,13,True,True,False,1
1,How do the costs of fire sales of assets in ma...,['| Cost of sales | Cost of sales | Cost of sa...,The provided sources do not contain informatio...,The costs of fire sales of assets in market eq...,1.000000,0.222524,0.000000,0.0,13,True,True,False,1
2,Under the capital requirements suggested under...,['## 1 INTRODUCTION\n\nIn order to prevent ban...,The provided sources do not contain informatio...,"Under the Basel III capital requirements, cons...",1.000000,0.218615,0.000000,0.0,13,True,True,False,1
3,"Under table-7.2.12, how does the projected imp...",['| | | | | | | | | | | | | | | | | | |\n|----...,The provided sources do not contain informatio...,"When RWAs are unchanged, a one-percentage poin...",1.000000,0.214094,0.000000,0.0,13,True,True,False,1
4,What table identifier and subject heading are ...,['<!-- formula-not-decoded -->\n\nG87G104G101G...,Error generating the answer.,"Table 6.5, titled 'Indicative Benchmarks for L...",0.000000,0.173999,0.000000,0.0,13,True,False,False,2
5,Under what specific regulatory provision of Re...,['* Indicates management contract or compensat...,Certain instruments defining the rights of hol...,Apple Inc. omitted the instruments pursuant to...,1.000000,0.971252,1.000000,1.0,13,True,True,False,1
6,If a wire transfer's ordering financial instit...,"[""- e. Cross-border wire transfer: Cross-borde...",It qualifies as a cross-border wire transfer. ...,It qualifies as a cross-border wire transfer. ...,1.000000,0.997334,1.000000,1.0,13,True,True,False,1
7,Based on the provided financial statement data...,['| Vendor non-trade receivables | Vendor non-...,Based on the cash flows statement data:\n\n- I...,'Inventories' reported a positive adjustment o...,1.000000,0.732563,0.200000,1.0,13,True,True,False,1
8,How is Systemic Risk described in relation to ...,"[""Changes or additions to the Company's supply...",The provided sources do not contain informatio...,Systemic Risk refers to the risk faced by the ...,1.000000,0.223145,0.000000,0.0,13,True,True,False,1
9,Which regulatory circular containing the code ...,['| 123. | UBD.BPD.CO./NSB1/11/12.03.000/ 2009...,The regulatory circular containing the code id...,The circular containing '12.05.001' issued in ...,1.000000,0.989166,1.000000,1.0,13,True,True,False,1
10,For Senior Management (such as Whole Time Dire...,['| Entity Level | Board Resolution @@ | Exemp...,An entity can satisfy the Proof of Identity re...,The entity can satisfy the requirement by decl...,1.000000,0.983733,1.000000,1.0,13,True,True,False,1
11,Based on the regulatory filing excerpt for App...,"[""| | | |\n|----|----|----|\n| | | |\n\ng66145...","Based on the filing, Apple Inc.'s state of inc...",Apple Inc.'s state of incorporation is Califor...,1.000000,0.994706,1.000000,1.0,13,True,True,False,1
12,"In 2025, how did the portion of the Company's ...","[""Markets and Distribution\n\nThe Company's cu...","During 2025, the Company's net sales through i...","In 2025, indirect distribution channels accoun...",1.000000,0.838405,1.000000,1.0,13,True,True,False,1
13,Under the section labeled 'G83G99G101G110G97G1...,['| G84G97G98G108G101G32G45G32G55G46G50G46G49G...,The provided sources are insufficient to answe...,The three values reported for 'G50G48G49G54' u...,0.666667,0.206080,0.000000,0.0,13,True,True,False,1
14,Under the model assumptions where the cost of ...,['| | | | | | | | | | | | | | | | | | | | | | ...,The provided sources do not contain informatio...,Short-term debt is defined as having a maturit...,1.000000,0.217780,0.000000,0.0,13,True,True,False,1
15,"Based on the author's calculations table, what...",['| | | | | | | | | | | | | | | | | | | | | | ...,The provided sources are insufficient to answe...,When RWAs is at its lowest recorded level of 7...,0.750000,0.208141,0.000000,0.0,13,True,True,False,1
16,Comparing the two cited papers co-authored by ...,"['2. Accordingly, in exercise of the powers co...",The provided sources do not contain informatio...,"""The Economics of Bank Regulation"" was publish...",1.000000,0.214613,0.000000,0.0,13,True,True,False,1
17,"Based on Apple Inc.'s 2025 Form 10-K, how did ...","[""Fourth Quarter 2025:\n\n• iPhone 17, iPhone ...","Fiscal year 2023 spanned 53 weeks, whereas fis...","Fiscal year 2023 spanned 53 weeks, whereas fis...",1.000000,0.997090,0.833333,1.0,13,True,True,False,1
18,What is the working paper number and publicati...,['| | | | | | | | | | | | | | | | | | | | | | ...,The provided sources do not contain informatio...,"The publication is Working Paper 14631, publis...",1.000000,0.199134,0.000000,0.0,13,True,True,False,1
19,What initial step is outlined to capture the e...,"[""prohibit any person from making funds, finan...",The provided sources do not contain informatio...,The initial step is analyzing the basic concep...,1.000000,0.215679,0.000000,0.0,13,True,True,False,1