In [5]:
import pandas as pd
path="compliance_benchmark.csv"
df=pd.read_csv(path)
df

,question,ground_truth,context
0,Under Management's Annual Report on Internal C...,Management evaluated the effectiveness of inte...,Management's Annual Report on Internal Control...
1,Under what circumstance does the confidentiali...,The confidentiality requirement does not inhib...,"Every RE, its directors, officers, and all emp..."
2,What technological and supplier-driven factors...,The factors include: (1) initial capacity cons...,The Company uses some custom components that a...
3,Under what condition and through what specific...,A customer's PAN details must be verified from...,"- ii. Customer's PAN details, if available wit..."
4,Under the regulatory provisions for Video-base...,When conducting CDD for a proprietorship firm ...,## 18. 62 REs may undertake V-CIP to carry out...
...,...,...,...
95,What are the standard minimum frequencies for ...,Standard periodic KYC updation must be carried...,## 38. 112 Updation / Periodic Updation of KYC...
96,What mandatory reporting obligation is imposed...,Upon becoming aware of any transactions and at...,The order shall be issued without prior notice...
97,Based on the filing status and compliance disc...,The Registrant is designated as a 'Large accel...,| | | | | | | | | | | | | | | | | | | | | |\n|...
98,"Based on amendment reference citations 28, 29,...",The chronological sequence from earliest to la...,[28 Amended vide circular DOR.AML.REC.111/14.0...
99,Which exhibit related to the 2022 Employee Sto...,Exhibit 10.11 (Form of CEO Performance Award A...,| 10.11* | 10.11* | 10.11* | | | | [Form of CE...

In [6]:
df2=pd.read_csv("final_evaluation_report.csv")

In [7]:
df2

,user_input,retrieved_contexts,response,reference,faithfulness,answer_correctness,context_precision,context_recall,num_contexts,is_safe,is_compliant,web_search_used,loop_count
0,Under Management's Annual Report on Internal C...,"[""Management's Annual Report on Internal Contr...",Management assessed the effectiveness of the C...,Management evaluated the effectiveness of inte...,1.0,0.997296,0.833333,1.0,11,True,True,False,1
1,Under what circumstance does the confidentiali...,"['Every RE, its directors, officers, and all e...",The confidentiality requirement does not inhib...,The confidentiality requirement does not inhib...,1.0,0.998826,1.000000,1.0,11,True,True,False,1
2,What technological and supplier-driven factors...,"[""Additionally, the Company's new products oft...","According to the sources, the technological an...",The factors include: (1) initial capacity cons...,1.0,0.663760,1.000000,1.0,11,True,True,False,1
3,Under what condition and through what specific...,"[""- i. No change in KYC information: In case o...","During the periodic updation of KYC, a Regulat...",A customer's PAN details must be verified from...,1.0,0.991691,1.000000,1.0,11,True,True,False,1
4,Under the regulatory provisions for Video-base...,['## 18. 62 REs may undertake V-CIP to carry o...,When conducting Customer Due Diligence (CDD) f...,When conducting CDD for a proprietorship firm ...,1.0,0.992966,1.000000,1.0,11,True,True,False,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,What are the standard minimum frequencies for ...,"[""## 38. 112 Updation / Periodic Updation of K...",Standard minimum frequencies for periodic KYC ...,Standard periodic KYC updation must be carried...,1.0,0.994728,1.000000,1.0,11,True,True,False,1
96,What mandatory reporting obligation is imposed...,['The order shall be issued without prior noti...,Upon becoming aware of any transactions and at...,Upon becoming aware of any transactions and at...,1.0,0.997937,1.000000,1.0,11,True,True,False,1
97,Based on the filing status and compliance disc...,"[""| | | | | | | | | | | | | | | | | | | | | |\...","Based on the provided disclosures, the Registr...",The Registrant is designated as a 'Large accel...,1.0,0.909370,1.000000,1.0,11,True,True,False,1
98,"Based on amendment reference citations 28, 29,...",['[28 Amended vide circular DOR.AML.REC.111/14...,The chronological sequence from earliest to la...,The chronological sequence from earliest to la...,1.0,0.989591,1.000000,1.0,11,True,True,False,1
99,Which exhibit related to the 2022 Employee Sto...,['| 10.11* | 10.11* | 10.11* | | | | [Form of ...,There are two exhibits related to the 2022 Emp...,Exhibit 10.11 (Form of CEO Performance Award A...,1.0,0.667392,1.000000,1.0,11,True,True,False,1